### PR TITLE
Q4 revision 2

### PR DESCRIPTION
**Pull request by slackmoehrle**
Starting docs overhaul

### CODE REVIEW

**Comment by drelaptop** [comment]
### part cmake docs should be removed

block 1 [Cocos2d-x Options]

https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/CMake-Guide.md#cocos2d-x-options

part2, [Prebuilt libraries feature]

https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/CMake-Guide.md#prebuilt-libraries-feature

**Comment by slackmoehrle** [comment]
@drelaptop - does this mean that prebuilt libraries are not supported any longer? We supported with `cocos` but dropped that and initially supported prebuilts with `CMake`. We need to tell the users this because many users are using prebuilts and this will cause a change for them. If we don't support prebuilts, I should draft a topic notifying them now instead of the when 3.17.1 is released.

**Comment by drelaptop** [comment]
developer can simply use cmake to reuse engine build. 

I remove it for @crazyhappygame reasonable advice. see https://github.com/cocos2d/cocos2d-x/pull/19109#issue-222070365 for detail.

today, I will new a post in English forum to discuss this issues.

**Comment by drelaptop** [comment]
I will try to change a more simple method to reuse engine libs.

**Comment by slackmoehrle** [comment]
Thank you for explaining.

**Comment by drelaptop** [comment]
Add this thread

https://discuss.cocos2d-x.org/t/not-elegant-cmake-prebuilt-feature-was-removed-in-3-17-1-release/44688

**Pull request merged**
