### PR TITLE
Fixed some small bugs.

### PR DESCRIPTION
**Pull request by hewenning**
The TTF label font sample code is incorrect.

### CODE REVIEW

**Comment by slackmoehrle** [comment]
I think you fixed some of these same items already: https://github.com/cocos2d/cocos2d-x-docs/pull/258 and it was merged. Did you forget to re-pull?

**Comment by hewenning** [comment]
这次修改的地方是关于UI组件，Label中的TTF字体的示例代码的错误。

**Comment by slackmoehrle** [comment]
But you are submitting some of the same changes as before. Why?

You submitted this: https://github.com/cocos2d/cocos2d-x-docs/pull/258
and notice the files you changed:
Screen Shot 2019-07-30 at 5 51 52 AM

Now, in this PR you are submitting some of the same changes AGAIN.
Screen Shot 2019-07-30 at 5 53 57 AM

Even though your previous PR was merged into `master` already.
Screen Shot 2019-07-30 at 5 55 03 AM

I don't understand why you are doing this. You should have cut a new branch from `master` before submitting your `LabelTTF` changes.

**Comment by hewenning** [comment]
Sorry, I used this feature for the first time.

**Comment by slackmoehrle** [comment]
It is OK. I'll merge over this time.

The normal work flow is something like:
```sh
git checkout master
git pull origin master
git checkout -b (some_branch_called_something)
(make your changes)
git add (some files)
git commit -m 'some message' (some files)
git push -u (your upstream) (some_branch_called_something)
```
then create the PR

next time you repeat these same steps first.

**Comment by hewenning** [comment]
OK，I am sorry to bring you trouble, thank you.

**Pull request merged**
